version: "3.8"

services:
  target_server:
    build: ./backend/target_server
    platform: linux/x86_64
    networks:
      - shared-network
    ports:
      - 8080:8080
    
  proxy_server:
    build: ./backend/proxy_server
    platform: linux/x86_64
    ports:
      - 3333:3333
    networks:
      - shared-network
    
  front:
    container_name: "vite_app"
    build: ./frontend
    platform: linux/x86_64
    command: sh -c "npm rebuild esbuild && yarn dev"
    ports:
      - 3000:3000
    networks:
      - shared-network
    volumes:
      - ./frontend:/app
networks:
  shared-network:

